version: '3.9'

services:

  authservice:
    image: authservice:0.0.1-SNAPSHOT
    container_name: authservice
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  jokeservice:
    image: jokeservice:0.0.1-SNAPSHOT
    container_name: jokeservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - authservice
    networks:
      - backend

  quoteservice:
    image: quoteservice:0.0.1-SNAPSHOT
    container_name: quoteservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - authservice
    networks:
      - backend

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - authservice
      - jokeservice
      - quoteservice
    networks:
      - backend

networks:
  backend: